WIP(sonarcloud GH Action)

diff --git a/.github/workflows/sonar-analysis.yml b/.github/workflows/sonar-analysis.yml
--- a/.github/workflows/sonar-analysis.yml
+++ b/.github/workflows/sonar-analysis.yml
@@ -53,6 +53,14 @@ jobs:
       - run: echo "always-auth=true" >> .npmrc
       - name: Install
         run: yarn
+      - name: Check and Install Playwright
+        run: |
+          if ! yarn list playwright > /dev/null 2>&1; then
+            echo "Playwright not found, installing..."
+            yarn playwright install
+          else
+            echo "Playwright is already installed."
+          fi
       - name: Unit test run
         run: yarn test:coverage
 
